---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- name: Read CephX libvirt authentication key
  ansible.builtin.command: "ceph auth get-key client.{{ ceph_client_libvirt }}"
  register: ceph_kvm_key_command

- name: Set CephX libvirt authentication key
  ansible.builtin.set_fact:
    kvm_cephx_auth_key: "{{ ceph_kvm_key_command.stdout }}"
  when: ceph_kvm_key_command.rc == 0

- name: Copy temporary RBD pool XML description
  ansible.builtin.template:
    src: rbd-pool.xml.j2
    dest: "{{ libvirt_tmp_pool_file_prefix }}-{{ kvm_rbd_pool_name }}.xml"
    owner: root
    group: root
    mode: 0644

- name: Check Ceph secrets doesn't yet exist in libvirt
  ansible.builtin.shell: virsh secret-list | grep {{ kvm_cephx_secret_guid }}
  register: libvirt_secret_list
  failed_when: false

- name: Copy temporary secret config
  ansible.builtin.template:
    src: rbd-secret.xml.j2
    dest: "{{ libvirt_tmp_pool_file_secret }}"
  when: libvirt_secret_list.rc == 1

- name: Create ceph secret
  ansible.builtin.shell: virsh secret-define --file "{{ libvirt_tmp_pool_file_secret }}"
  register: rbd_secret_id
  when: libvirt_secret_list.rc == 1

- name: Populate RBD secret with values
  ansible.builtin.command: "virsh secret-set-value --secret {{ kvm_cephx_secret_guid }} --base64 {{ kvm_cephx_auth_key }}"

- name: Check for RBD pool existence
  ansible.builtin.command: "virsh pool-info {{ kvm_rbd_pool_name }}"
  register: kvm_rbd_pool_info
  changed_when: false
  failed_when: false

- name: Define rbd pool
  ansible.builtin.command: "virsh pool-define {{ libvirt_tmp_pool_file_prefix }}-{{ kvm_rbd_pool_name }}.xml"
  when: kvm_rbd_pool_info.rc != 0

- name: Autostart RBD pool
  ansible.builtin.command: "virsh pool-autostart {{ kvm_rbd_pool_name }}"
  when: kvm_rbd_pool_info.rc != 0

- name: Start RBD pools
  ansible.builtin.command: "virsh pool-start {{ kvm_rbd_pool_name }}"
  when: kvm_rbd_pool_info.rc != 0

- name: Remove temporary pool definition files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ libvirt_tmp_pool_file_prefix }}-{{ kvm_rbd_pool_name }}.xml"
    - "{{ libvirt_tmp_pool_file_secret }}"
