---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- name: restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: true

- name: stop keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: stopped
    enabled: false

- name: reload sysctl
  ansible.builtin.shell: sysctl --system
