---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- import_tasks: iptables.yml
  when:
    - wan_access
    - kowabunga_firewall_mode == 'iptables'

- import_tasks: nftables.yml
  when: kowabunga_firewall_mode == 'nftables'
