argument_specs:

  main:
    short_description: Install and configures client-side and server-side metrology components.
    description:
      - Install and configures client-side and server-side metrology components.

    options:
      kowabunga_metrology_enabled:
        description:
          - Enable metrology-related components deployment.
          - Useless if you do not care about monitoring or are using your own metrology agents.
        type: bool
        default: false

      kowabunga_metrology_dashboard_enabled:
        description:
          - Enable logs/metrics dashboard component.
          - Provided by Grafana.

      kowabunga_metrology_dashboard_admin_user:
        description:
          - Admin user name for dashboard component.
        type: str
        default: kowabunga

      kowabunga_metrology_dashboard_admin_password:
        description:
          - Admin password for dashboard component.
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
          - Empty if unspecified.
        type: str
        default: "{{ secret_kowabunga_metrology_dashboard_admin_password }}"

      kowabunga_metrology_dashboard_extra_users:
        description:
          - A list of extra users to be added to dashboard component.
        type: list
        elements: dict
        default: []
        options:
          name:
            description:
              - Friendly user name.
              - "Example: John Doe."
            type: str
            required: true
          email:
            description:
              - User email address.
            type: str
            required: true
          login:
            description:
              - User short name (a.k.a. login id).
              - "Example: 'jdoe'."
            type: str
            required: true
          password:
            description:
              - User password.
              - Recommended to be safe and encrypted into Ansible Vault or SOPS.
            type: str
            required: true

      kowabunga_metrology_dashboard_public_url:
        description:
          - Public FQDN for dashboard component.
          - Usually something such as "https://grafana.acme.com".
        type: str
        default: ''

      kowabunga_metrology_agent_target_relabelling_rules:
        description:
          - Optionally defines a list of default target relabelling rules after scrapping.
          - See https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.relabel/ for details.
        type: list
        elements: dict
        default: []
        options:
          sources:
            description:
              - The list of labels whose values are to be selected.
            type: list
            elements: str
          target:
            description:
              - Label to which the resulting value will be written to.
            type: str
          action:
            description:
              - The relabeling action to perform.
            type: str
            default: replace
            choices: ['drop', 'dropequal', 'hashmod', 'keep', 'keepequal', 'labeldrop', 'labelkeep', 'labelmap', 'lowercase', 'replace', 'uppercase']
          replacement:
            description:
              - The value against which a regular expression replace is performed, if the regular expression matches the extracted value.
              - Supports previously captured groups.
            type: str
          regex:
            description:
              - A valid RE2 expression with support for parenthesized capture groups.
              - Used to match the extracted value from the combination of the source_label and separator fields or filter labels during the labelkeep/labeldrop/labelmap actions.
            type: str
          separator:
            description:
              - The separator used to concatenate the values present in source_labels.
            default: ';'

      kowabunga_metrology_agent_metrics_enabled:
        description:
          - Enable metrics collection agent on host.
          - Provided by Grafana Alloy.
        type: bool
        default: false

      kowabunga_metrology_agent_metrics_extra_exporters:
        description:
          - List of optional external Prometheus exporters to pull metrics from.
        type: list
        elements: dict
        default: []
        options:
          name:
            description:
              - Friendly name of the Prometheus exporter to scrape.
            type: str
            required: true
          address:
            description:
              - IP address of the Prometheus exporter to scrape
              - Defaults to private network address if unspecified.
            type: str
          port:
            description:
              - Port of the Prometheus exporter to scrape.
            type: int
            required: true
          path:
            description:
              - URL path of the Prometheus exporter to scrape.
            type: str
            default: /metrics
          interval:
            description:
              - Polling frequency of the Prometheus exporter to scrape.
            type: str
            default: 15s
          extra_labels:
            description:
              - List of key/values labels to be appended to scraped metrics.
            type: list
            elements: dict
            options:
              key:
                description:
                  - Label name to be appended.
                type: str
              value:
                description:
                  - Label value to be appended.
                type: str

      kowabunga_metrology_agent_metrics_relabelling_rules:
        description:
          - Optionally defines a list of default metrics relabelling rules after scrapping.
          - See https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.relabel/ for details.
        type: list
        elements: dict
        default: []
        options:
          sources:
            description:
              - The list of labels whose values are to be selected.
            type: list
            elements: str
          target:
            description:
              - Label to which the resulting value will be written to.
            type: str
          action:
            description:
              - The relabeling action to perform.
            type: str
            default: replace
            choices: ['drop', 'dropequal', 'hashmod', 'keep', 'keepequal', 'labeldrop', 'labelkeep', 'labelmap', 'lowercase', 'replace', 'uppercase']
          replacement:
            description:
              - The value against which a regular expression replace is performed, if the regular expression matches the extracted value.
              - Supports previously captured groups.
            type: str
          regex:
            description:
              - A valid RE2 expression with support for parenthesized capture groups.
              - Used to match the extracted value from the combination of the source_label and separator fields or filter labels during the labelkeep/labeldrop/labelmap actions.
            type: str
          separator:
            description:
              - The separator used to concatenate the values present in source_labels.
            default: ';'

      kowabunga_metrology_agent_metrics_extra_labels:
        description:
          - Dictionnary of extra labels to be appended each metrics before being shipped to time-series database(s).
          - "Format is 'label_name: label_value'"
        type: dict
        default: {}

      kowabunga_metrology_agent_metrics_blacklisted_regex:
        description:
          - List of collected metrics regex to be dropped (i.e. not remotely shipped).
          - Allows saving bandwidth and processing power, minimizing amount of collected timeseries.
          - Supports globbing.
          - "Examples: ['go_.*', 'promhttp_.*'] ..."
        type: list
        elements: str
        default: []

      kowabunga_metrology_agent_logs_enabled:
        description:
          - Enable logs collection agent on host.
          - Provided by Grafana Alloy.
        type: bool
        default: false

      kowabunga_metrology_agent_logs_files_extra:
        description:
          - List of external log files to pull from.
          - Supports globbing.
          - "Example: ['/var/log/dpkg.log']"
        type: str
        default: []

      kowabunga_metrology_server_metrics_enabled:
        description:
          - Enable metrics collection server on host.
          - Provided by Victoria Metrics.
        type: bool
        default: false

      kowabunga_metrology_server_metrics_retention_period:
        description:
          - Set server-side metrics retention period.
        type: str
        default: 30d

      kowabunga_metrology_server_metrics_public_url:
        description:
          - Public FQDN for metrics collection server.
          - Usually something such as "https://metrics.acme.com".
        type: str
        default: ''

      kowabunga_metrology_server_metrics_auth_user:
        description:
          - User name used by metrology agent to push metrics to server.
          - Used for HTTPS basic authentication.
        type: str
        default: metrics

      kowabunga_metrology_server_metrics_auth_password:
        description:
          - User password used by metrology agent to push metrics to server.
          - Used for HTTPS basic authentication (disabled if unspecified).
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
        type: str
        default: "{{ secret_kowabunga_metrology_server_metrics_auth_password }}"

      kowabunga_metrology_server_logs_enabled:
        description:
          - Enable logs collection server on host.
          - Provided by Victoria Logs.
        type: bool
        default: false

      kowabunga_metrology_server_logs_retention_period:
        description:
          - Set server-side logs retention period.
        type: str
        default: 30d

      kowabunga_metrology_server_logs_public_url:
        description:
          - Public FQDN for logs collection server.
          - Usually something such as "https://logs.acme.com".
        type: str
        default: ''

      kowabunga_metrology_server_logs_auth_user:
        description:
          - User name used by metrology agent to push logs to server.
          - Used for HTTPS basic authentication.
        type: str
        default: logs

      kowabunga_metrology_server_logs_auth_password:
        description:
          - User password used by metrology agent to push logs to server.
          - Used for HTTPS basic authentication (disabled if unspecified).
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
        type: str
        default: "{{ secret_kowabunga_metrology_server_logs_auth_password }}"
