argument_specs:

  main:
    short_description: Install and configures client-side and server-side metrology components.
    description:
      - Install and configures client-side and server-side metrology components.

    options:
      kowabunga_metrology_enabled:
        description:
          - Enable metrology-related components deployment.
          - Useless if you do not care about monitoring or are using your own metrology agents.
        type: bool
        default: false

      kowabunga_metrology_dashboard_enabled:
        description:
          - Enable logs/metrics dashboard component.
          - Provided by Grafana.

      kowabunga_metrology_dashboard_admin_user:
        description:
          - Admin user name for dashboard component.
        type: str
        default: kowabunga

      kowabunga_metrology_dashboard_admin_password:
        description:
          - Admin password for dashboard component.
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
          - Empty if unspecified.
        type: str
        default: "{{ secret_kowabunga_metrology_dashboard_admin_password }}"

      kowabunga_metrology_dashboard_extra_users:
        description:
          - A list of extra users to be added to dashboard component.
        type: list
        elements: dict
        default: []
        options:
          name:
            description:
              - Friendly user name.
              - "Example: John Doe."
            type: str
            required: true
          email:
            description:
              - User email address.
            type: str
            required: true
          login:
            description:
              - User short name (a.k.a. login id).
              - "Example: 'jdoe'."
            type: str
            required: true
          password:
            description:
              - User password.
              - Recommended to be safe and encrypted into Ansible Vault or SOPS.
            type: str
            required: true

      kowabunga_metrology_dashboard_public_url:
        description:
          - Public FQDN for dashboard component.
          - Usually something such as "https://grafana.acme.com".
        type: str
        default: ''

      kowabunga_metrology_agent_metrics_enabled:
        description:
          - Enable metrics collection agent on host.
          - Provided by Grafana Alloy.
        type: bool
        default: false

      kowabunga_metrology_agent_logs_enabled:
        description:
          - Enable logs collection agent on host.
          - Provided by Grafana Alloy.
        type: bool
        default: false

      kowabunga_metrology_server_metrics_enabled:
        description:
          - Enable metrics collection server on host.
          - Provided by Victoria Metrics.
        type: bool
        default: false

      kowabunga_metrology_server_metrics_retention_period:
        description:
          - Set server-side metrics retention period.
        type: str
        default: 30d

      kowabunga_metrology_server_logs_enabled:
        description:
          - Enable logs collection server on host.
          - Provided by Victoria Logs.
        type: bool
        default: false
