---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- name: Install packages
  ansible.builtin.apt:
    name: chrony
    state: latest
    update_cache: true
  notify: Restart chrony

- name: Set configuration settings
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "/etc/chrony/chrony.conf"
    mode: 0644
    owner: root
    group: root
  notify: Restart chrony

- name: Enable chrony
  ansible.builtin.systemd_service:
    name: chrony
    enabled: true
    state: started
