---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- name: Install Metadata Server
  ansible.builtin.apt:
    name: ceph-mds
    state: present
  notify: Restart ceph-mds

- ansible.builtin.import_tasks: systemd.yml
  vars:
    service: "ceph-mds"

- name: Create runtime directory for metadata server
  ansible.builtin.file:
    path: "/var/lib/ceph/mds/ceph-{{ ansible_hostname }}"
    state: directory
    owner: ceph
    group: ceph
    mode: 0755

- name: Check if metadata server has already been configured and deployed
  ansible.builtin.stat:
    path: "/var/lib/ceph/mds/ceph-{{ ansible_hostname }}/keyring"
  register: ceph_mds_done
  when: ceph_auth_enabled

- name: Configure auth key for cephx if auth is enabled
  ansible.builtin.shell:
    cmd: "ceph auth get-or-create mds.{{ ansible_hostname }} mon 'profile mds' mgr 'profile mds' mds 'allow *' osd 'allow *' > /var/lib/ceph/mds/ceph-{{ ansible_hostname }}/keyring"
  when:
    - ceph_auth_enabled
    - not ceph_mds_done.stat.exists

- name: Enable metadata server
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - ceph.target
    - "ceph-mds@{{ ansible_hostname }}"
