---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- name: Increase max PG-per-OSD setting
  ansible.builtin.shell: "ceph config set mon mon_max_pg_per_osd {{ kowabunga_ceph_osd_max_pg_per_osd }}"

- name: Check for pool existence
  ansible.builtin.shell: "ceph osd pool get {{ item.name }} size"
  register: ceph_pools
  changed_when: false
  failed_when: false
  loop: "{{ kowabunga_ceph_osd_pools }}"
  when: item.when | default(true)

- name: Create pool on OSD
  ansible.builtin.shell: "ceph osd pool create {{ item.name }} {{ item.pgs }} {{ item.pgs }} replicated"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0

- name: Enable pool
  ansible.builtin.shell: "ceph osd pool application enable {{ item.name }} {{ item.name }}"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0
    - item.ptype != 'fs'

- name: Set pool replication size
  ansible.builtin.shell: "ceph osd pool set {{ item.name }} size {{ item.replication.request }}"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0

- name: Set pool minimum replication size
  ansible.builtin.shell: "ceph osd pool set {{ item.name }} min_size {{ item.replication.min }}"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0

- name: Set pool compression settings
  ansible.builtin.shell: "ceph osd pool set {{ item.name }} compression_mode {{ item.compression.mode | default('passive') }}"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0

- name: Set pool compression algorithm
  ansible.builtin.shell: "ceph osd pool set {{ item.name }} compression_algorithm {{ item.compression.algorithm | default('snappy') }}"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0

- name: Initialize pool
  ansible.builtin.shell: "rbd pool init {{ item.name }}"
  loop: "{{ kowabunga_ceph_osd_pools }}"
  loop_control:
    index_var: idx
  when:
    - ceph_pools.results[idx].rc is defined
    - ceph_pools.results[idx].rc != 0
    - item.ptype == "rbd"
