---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

mongodb_version: 8.0
mongodb_apt_keyring_remote: "https://pgp.mongodb.com/server-{{ mongodb_major_version }}.asc"
mongodb_apt_keyring_local: /etc/apt/keyrings/mongodb.asc
mongodb_dbpath: /var/lib/mongodb
mongodb_logpath: /var/log/mongodb
mongodb_keyfile: "{{ mongodb_dbpath }}/key"
mongodb_port: 27017
mongodb_max_connections: 1024
mongodb_profiling: "slowOp"

mongodb_script_rs_init: /tmp/mongo.rs-init.js
mongodb_script_admin_init: /tmp/mongo.admin.js
mongodb_script_users_init: /tmp/mongo.users.js

mongodb_rs_hosts: "{{ ansible_play_hosts_all }}"

mongodb_packages_list:
  - mongodb-org-server
  - mongodb-org-shell
  - mongodb-org-tools
  - mongodb-mongosh

#######################
# Host Control Plugin #
#######################

hostctl_plugins_mongodb:
  - name: mongodb
    when: "{{ kowabunga_mongodb_enabled }}"
