argument_specs:

  main:
    short_description: Install, configure, and start Kiwi node.
    description:
      - Install, configure, and start Kowabunga Kiwi SDN node.

    options:
      kowabunga_kiwi_loglevel:
        description:
          - Kahuna Kiwi agent log level.
        type: str
        default: INFO
        choices: ['INFO', 'DEBUG', 'WARNING', 'CRITICAL']

      kowabunga_kiwi_agent_id:
        description:
          - ID of the Kowabunga Kiwi agent, as instructed in Kahuna database.
          - Used by agent to establish WebSocket connection to Kahuna.
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
          - Defaults to encrypted V(secret_kowabunga_kiwi_agent_id) variable.
        type: str
        required: true

      kowabunga_kiwi_agent_api_key:
        description:
          - API key of the Kowabunga Kiwi agent, as instructed in Kahuna database.
          - Used by agent to establish WebSocket connection to Kahuna.
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
          - Defaults to encrypted V(secret_kowabunga_kiwi_agent_api_key) variable.
        type: str
        required: true
