---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- hosts: kaktus

  roles:
    - name: kowabunga.cloud.os
    - name: kowabunga.cloud.netplan
      when: kowabunga_netplan_config != {}
      tags: netplan
    - name: kowabunga.cloud.metrology
      when: kowabunga_metrology_enabled
      tags: metrology
    - name: kowabunga.cloud.kaktus
