---
# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

- name: Install Kowabunga Kahuna orchestrator
  ansible.builtin.apt:
    name: kowabunga-kahuna
    update_cache: true
    state: latest
  notify: restart kowabunga-kahuna

- name: Configure Kahuna
  ansible.builtin.template:
    src: kahuna.yml.j2
    dest: /etc/kowabunga/kahuna.yml
    owner: kahuna
    group: kowabunga
    mode: 0640
  no_log: true
  notify: restart kowabunga-kahuna

- name: Install Kowabunga Koala WebUI
  ansible.builtin.apt:
    name: kowabunga-koala
    state: latest
  notify: reload caddy
  when: kowabunga_koala_enabled

- name: Hash metric password
  when: kowabunga_metrology_server_metrics_auth_password != ''
  block:
    - name: Generate random metric password hash
      ansible.builtin.command: caddy hash-password -p '{{ kowabunga_metrology_server_metrics_auth_password }}'
      register: metrics_hash

    - name: Assign hash
      ansible.builtin.set_fact:
        tmp_metrics_auth_password_hash: "{{ metrics_hash.stdout }}"
      when: metrics_hash.rc == 0

- name: Set Caddy virtual host
  template:
    src: caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: 0644
  notify: reload caddy
