argument_specs:

  main:
    short_description: Install, configure, and start Kaktus node.
    description:
      - Install, configure, and start Kowabunga Kaktus HCI node.

    options:
      kowabunga_kaktus_loglevel:
        description:
          - Kahuna Kaktus agent log level.
        type: str
        default: INFO
        choices: ['INFO', 'DEBUG', 'WARNING', 'CRITICAL']

      kowabunga_kaktus_agent_id:
        description:
          - ID of the Kowabunga Kaktus agent, as instructed in Kahuna database.
          - Used by agent to establish WebSocket connection to Kahuna.
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
          - Defaults to encrypted V(secret_kowabunga_kaktus_agent_id) variable.
        type: str
        required: true

      kowabunga_kaktus_agent_api_key:
        description:
          - API key of the Kowabunga Kaktus agent, as instructed in Kahuna database.
          - Used by agent to establish WebSocket connection to Kahuna.
          - Recommended to be safe and encrypted into Ansible Vault or SOPS.
          - Defaults to encrypted V(secret_kowabunga_kaktus_agent_api_key) variable.
        type: str
        required: true

      kowabunga_kaktus_ceph_monitor_name:
        description:
          - Ceph cluster monitor hostname to be used by Kaktus agent to connect to.
          - Defaults to local V(ansible_hostname) if unspecified.
        type: str

      kowabunga_kaktus_ceph_monitor_host:
        description:
          - Ceph cluster monitor host address to be used by Kaktus agent to connect to.
          - Defaults to local V(kowabunga_ceph_monitor_listen_addr) if unspecified.
        type: str
